spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/atl_academy_07
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
#   generate-ddl: true
    show-sql: true
#    hibernate:
#          ddl-auto: update
  liquibase:
     change-log: classpath:liquibase/1.0/changelog-4.sql
  mvc:
    static-path-pattern: /content/**



springdoc:
  apiDocs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: 'true'


server:
  port: 8000